<a href="https://colab.research.google.com/github/radziot/data-science-bootcamp/blob/main/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Tensorflow
>Strona biblioteki: [https://www.tensorflow.org/](https://www.tensorflow.org/)  
>Dokumentacja: [https://www.tensorflow.org/api_docs](https://www.tensorflow.org/api_docs)  
>
>Szybko rozwijająca się biblioteka do uczenia maszynowego i uczenia głębokiego rozwijana przez Google.
>
>Aby zainstalować bibliotekę tensorflow, użyj polecenia poniżej:
```
pip install tensorflow
```

### Keras
>Strona biblioteki: [https://keras.io/](https://keras.io/)  
>
>Wysokopoziomowy interfejs do budowy sieci neuronowych. Działa zarówno na Tensorflow, Theano oraz CNTK.
>
>Aby zainstalować bibliotekę keras, użyj polecenia poniżej:
```
pip install keras
```

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Załadowanie biblioteki tensorflow


In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.15.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [3]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda *.summary()*

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44 (176.00 Byte)
Trainable params: 44 (176.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Dodanie kolejnej warstwy

In [5]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54 (216.00 Byte)
Trainable params: 54 (216.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [6]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [7]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [10]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [11]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [12]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [13]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [14]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [15]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [16]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97 (388.00 Byte)
Trainable params: 97 (388.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [17]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [19]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [20]:
data[:3]

array([[ 1.15513294e+00,  2.09051943e+00, -3.13661044e-01,
         1.55994638e+00, -1.71096827e+00,  7.41341905e-01,
         4.71949775e-01,  1.86715500e-01,  6.67634846e-01,
        -8.02528267e-01, -7.46966660e-03, -7.73787897e-01,
         4.59483072e-01, -7.36104251e-01, -9.08571128e-01,
        -2.65776889e+00, -2.83044739e-01,  9.86427681e-01,
         1.26077227e+00, -1.43319027e+00, -9.09941777e-02,
         1.96003288e-01, -1.87537851e+00, -7.96571120e-01,
        -1.26689164e+00,  1.56793745e-01,  5.64039876e-01,
         1.08385047e+00,  1.08760648e+00,  6.62767975e-01,
         1.04428477e+00, -5.65503290e-01,  9.47107923e-01,
         1.52676398e+00, -2.55106060e-01,  3.02512147e-01,
         1.77202202e+00,  2.02220172e+00, -4.94823479e-01,
        -7.81619615e-01, -1.10694978e+00, -3.79088318e-01,
         8.14034827e-01,  1.27223723e+00, -6.60695557e-01,
         2.25846508e+00, -9.51540656e-01,  7.57862260e-02,
         1.66006758e-01,  1.92843876e+00,  4.88144143e-0

In [21]:
labels[:10]

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1]])

In [22]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 2s 3ms/step - loss: 0.7447 - accuracy: 0.5032
Epoch 2/20
313/313 [==============================] - 1s 3ms/step - loss: 0.6949 - accuracy: 0.5438
Epoch 3/20
313/313 [==============================] - 1s 3ms/step - loss: 0.6760 - accuracy: 0.5747
Epoch 4/20
313/313 [==============================] - 1s 3ms/step - loss: 0.6620 - accuracy: 0.5994
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6489 - accuracy: 0.6199
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6367 - accuracy: 0.6400
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6237 - accuracy: 0.6568
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6116 - accuracy: 0.6708
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5979 - accuracy: 0.6829
Epoch 10/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5865 - accuracy: 0.6894

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Train on 10000 samples
Epoch 1/20
10000/10000 [==============================] - 1s 70us/sample - loss: 0.7522 - accuracy: 0.5069
Epoch 2/20
10000/10000 [==============================] - 0s 28us/sample - loss: 0.7010 - accuracy: 0.5396
Epoch 3/20
10000/10000 [==============================] - 0s 28us/sample - loss: 0.6834 - accuracy: 0.5678
Epoch 4/20
10000/10000 [==============================] - 0s 28us/sample - loss: 0.6711 - accuracy: 0.5866
Epoch 5/20
10000/10000 [==============================] - 0s 29us/sample - loss: 0.6596 - accuracy: 0.6063
Epoch 6/20
10000/10000 [==============================] - 0s 27us/sample - loss: 0.6489 - accuracy: 0.6277
Epoch 7/20
10000/10000 [==============================] - 0s 29us/sample - loss: 0.6382 - accuracy: 0.6488
Epoch 8/20
10000/10000 [==============================] - 0s 28us/sample - loss: 0.6272 - accuracy: 0.6633
Epoch 9/20
10000/10000 [==============================] - 0s 27us/sample - loss: 0.6161 - accuracy: 0.6773
Epoch 10/20
10

In [23]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 1s 3ms/step - loss: 0.7548 - accuracy: 0.4965 - val_loss: 0.7323 - val_accuracy: 0.4855
Epoch 2/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6966 - accuracy: 0.5428 - val_loss: 0.7300 - val_accuracy: 0.4910
Epoch 3/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6761 - accuracy: 0.5699 - val_loss: 0.7294 - val_accuracy: 0.4915
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6611 - accuracy: 0.5949 - val_loss: 0.7309 - val_accuracy: 0.4940
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6466 - accuracy: 0.6223 - val_loss: 0.7360 - val_accuracy: 0.4885
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6320 - accuracy: 0.6435 - val_loss: 0.7420 - val_accuracy: 0.4885
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6173 - accuracy: 0.6633 - val_loss: 0.7481 - val_accuracy: 0.4850
Epoch 

In [24]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [25]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [26]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 [==============================] - 1s 3ms/step - loss: 0.7620 - accuracy: 0.4997 - val_loss: 0.7345 - val_accuracy: 0.4905
Epoch 2/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6971 - accuracy: 0.5515 - val_loss: 0.7314 - val_accuracy: 0.4970
Epoch 3/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6742 - accuracy: 0.5835 - val_loss: 0.7327 - val_accuracy: 0.4940
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6566 - accuracy: 0.6136 - val_loss: 0.7336 - val_accuracy: 0.4980
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6414 - accuracy: 0.6335 - val_loss: 0.7370 - val_accuracy: 0.5015
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6272 - accuracy: 0.6479 - val_loss: 0.7440 - val_accuracy: 0.4915
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6120 - accuracy: 0.6737 - val_loss: 0.7514 - val_accuracy: 0.4940
Epoch 

In [27]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [28]:
model.predict(test_data)

1/1 [==============================] - 0s 115ms/step


array([[0.11887848],
       [0.5889477 ],
       [0.26405025],
       [0.4563421 ],
       [0.13257769]], dtype=float32)

In [29]:
model.predict_proba(test_data)

AttributeError: 'Sequential' object has no attribute 'predict_proba'

In [30]:
model.predict_classes(test_data)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [ ]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [ ]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
labels[:10]

array([[2],
       [6],
       [8],
       [3],
       [0],
       [3],
       [9],
       [6],
       [7],
       [0]])

In [ ]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
labels[1]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 140us/sample - loss: 2.3235 - accuracy: 0.0980 - val_loss: 2.3153 - val_accuracy: 0.0985
Epoch 2/30
8000/8000 [==============================] - 0s 60us/sample - loss: 2.3052 - accuracy: 0.1047 - val_loss: 2.3040 - val_accuracy: 0.0995
Epoch 3/30
8000/8000 [==============================] - 1s 63us/sample - loss: 2.3031 - accuracy: 0.1009 - val_loss: 2.3104 - val_accuracy: 0.1090
Epoch 4/30
8000/8000 [==============================] - 1s 63us/sample - loss: 2.3016 - accuracy: 0.1039 - val_loss: 2.3061 - val_accuracy: 0.1065
Epoch 5/30
8000/8000 [==============================] - 0s 60us/sample - loss: 2.3005 - accuracy: 0.1155 - val_loss: 2.3084 - val_accuracy: 0.0990
Epoch 6/30
8000/8000 [==============================] - 0s 61us/sample - loss: 2.2979 - accuracy: 0.1119 - val_loss: 2.3134 - val_accuracy: 0.0985
Epoch 7/30
8000/8000 [==============================] - 0s 62us/sampl

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.09911948, 0.11620636, 0.07320527, 0.15997937, 0.08313195,
        0.11985189, 0.07282171, 0.08499081, 0.09132902, 0.09936419],
       [0.10808039, 0.11060798, 0.1585828 , 0.04076305, 0.11867085,
        0.11622953, 0.10032436, 0.10682581, 0.06562724, 0.07428803],
       [0.0535747 , 0.0826021 , 0.15126106, 0.04798588, 0.03644897,
        0.08196826, 0.17952028, 0.07557219, 0.14473361, 0.14633295],
       [0.12001421, 0.15575112, 0.13602467, 0.08515704, 0.06826283,
        0.06773269, 0.0736742 , 0.08663882, 0.09184736, 0.11489701],
       [0.1503428 , 0.14404033, 0.20681618, 0.0435313 , 0.07448085,
        0.05074822, 0.06210018, 0.0954838 , 0.08630197, 0.08615443],
       [0.09830751, 0.07327876, 0.17003337, 0.14070372, 0.07893839,
        0.0776796 , 0.12669246, 0.09419221, 0.07801841, 0.06215557],
       [0.05894386, 0.06890954, 0.10082155, 0.08828751, 0.06637203,
        0.16312268, 0.15596974, 0.08681998, 0.09833211, 0.11242106],
       [0.07287443, 0.06215156, 0.2424068

In [ ]:
model.predict_classes(test_data)

array([3, 2, 6, 1, 2, 2, 5, 2, 4, 2])

### <a name='a6'></a> Przykład - regresja

In [ ]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [ ]:
labels[:10]

array([ 2.76589765, 26.25951681, 42.46470588, 33.45842006,  6.10047945,
       42.16472461,  0.06071142,  9.63306066,  7.97318495, 49.39214105])

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 99us/sample - loss: 269.9293 - val_loss: 207.3698
Epoch 2/30
8000/8000 [==============================] - 0s 60us/sample - loss: 208.6766 - val_loss: 207.3182
Epoch 3/30
8000/8000 [==============================] - 0s 57us/sample - loss: 208.1491 - val_loss: 208.2676
Epoch 4/30
8000/8000 [==============================] - 0s 58us/sample - loss: 207.8588 - val_loss: 207.4424
Epoch 5/30
8000/8000 [==============================] - 0s 58us/sample - loss: 207.5430 - val_loss: 207.8541
Epoch 6/30
8000/8000 [==============================] - 0s 58us/sample - loss: 207.2514 - val_loss: 209.6800
Epoch 7/30
8000/8000 [==============================] - 0s 60us/sample - loss: 206.8425 - val_loss: 208.7884
Epoch 8/30
8000/8000 [==============================] - 0s 59us/sample - loss: 206.7675 - val_loss: 207.5888
Epoch 9/30
8000/8000 [==============================] - 0s 58us/sample - loss: 2

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/10
8000/8000 [==============================] - 1s 107us/sample - loss: 13.3688 - mse: 250.6315 - val_loss: 12.4057 - val_mse: 207.8904
Epoch 2/10
8000/8000 [==============================] - 0s 58us/sample - loss: 12.4745 - mse: 209.1429 - val_loss: 12.4120 - val_mse: 208.6593
Epoch 3/10
8000/8000 [==============================] - 1s 64us/sample - loss: 12.4606 - mse: 208.5854 - val_loss: 12.3944 - val_mse: 207.4827
Epoch 4/10
8000/8000 [==============================] - 0s 58us/sample - loss: 12.4351 - mse: 208.3050 - val_loss: 12.4262 - val_mse: 209.8297
Epoch 5/10
8000/8000 [==============================] - 0s 58us/sample - loss: 12.4279 - mse: 207.8135 - val_loss: 12.4113 - val_mse: 208.1427
Epoch 6/10
8000/8000 [==============================] - 0s 59us/sample - loss: 12.4111 - mse: 207.7288 - val_loss: 12.4030 - val_mse: 207.9031
Epoch 7/10
8000/8000 [==============================] - 0s 62us/sample - loss: 12.3957 - mse:

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[25.318836],
       [25.124805],
       [26.249212],
       [26.726828],
       [24.240023],
       [26.99018 ],
       [22.903202],
       [25.071842],
       [22.852095],
       [25.543777]], dtype=float32)